# Serverless definition file
# --------------------------
# Defines Lambda functions to be deployed to AWS using the Serverless Framework.
# http://serverless.com

service: restcharts

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  memorySize: 512
  timeout: 10
  environment: ${file(serverless.env.yml):${self:provider.stage}}

functions:
  app:
    handler: LambdaHandlers.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{any+}
          method: ANY
          cors: true
