# Serverless definition file
# --------------------------
# Defines Lambda functions to be deployed to AWS using the Serverless Framework.
# http://serverless.com

service: restcharts

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  memorySize: 512
  timeout: 10
  environment: ${file(env.yml):${self:provider.stage}}

functions:
  home:
    handler: LambdaHandlers.home
    events:
      - http:
          path: /
          method: get

  # Generate & Deliver Chart ---------------------------------------------------
  getChart:
    handler: LambdaHandlers.getChart
    events:
      - http:
          path: /chart/{type}
          method: get
          cors: true
      - http:
          path: /chart/{type}
          method: post
          cors: true
